### ISSUE TITLE
Printtrafo_CHK.pretty should be renamed

### ISSUE THREAD

**Issue by michal777** [KiCad/Printtrafo_CHK.pretty#1]
Is "printtrafo" english word? Maybe "Transformers_CHK" will sound better?

**Comment by CarlPoirier** [comment]
I believe it's in Deutsch. It's a relic from the old .mod library.

**Comment by CarlPoirier** [comment]
There is a new repository called "Transformers_CHK.pretty". This one will stay for a while until people update their fp-lib-table.

**Comment by wiebus** [comment]
Hello.

> Is "printtrafo" english word? Maybe "Transformers_CHK" will sound 
> better?

It is a mixture from english "print" and german short "trafo" for
"transformator" which means transformer. Of course, it is bad tech slang
and is used for those transformers wich can inserted in printed circuit
boards.

"CHK" is just the name of a manufacturer.

With best regards: Bernd Wiebus alias dl1eic


Am Donnerstag, den 12.03.2015, 14:54 -0700 schrieb michal777:
